# Generated by Django 3.2.8 on 2021-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
