# Generated by Django 3.2.8 on 2021-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_alter_subscriber_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='url',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
